name: Release Management

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      # https://github.com/release-drafter/release-drafter
      - uses: release-drafter/release-drafter@v5.6.1
        env:
          # using a PAT here will allow releases to trigger a build/release
          # but for this example, we're just using the actions token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
